[graph]
all-features = true

[advisories]
ignore = []

[licenses]
allow = ["MIT", "Apache-2.0"]
confidence-threshold = 0.95
exceptions = [
    { allow = ["Unicode-3.0"], crate = "unicode-ident" },
    { allow = ["Unicode-3.0"], crate = "yoke" },
    { allow = ["Unicode-3.0"], crate = "yoke-derive" },
    { allow = ["Unicode-3.0"], crate = "zerofrom" },
    { allow = ["Unicode-3.0"], crate = "zerofrom-derive" },
    { allow = ["BSD-2-Clause"], crate = "arrayref" },
    { allow = ["BSD-3-Clause"], crate = "tiny-skia" },
    { allow = ["BSD-3-Clause"], crate = "tiny-skia-path" },
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
    { crate = "bitflags@1.3.2", reason = "tiny-skia uses older png, leading to this older transient dep" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
