repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
    args: [--all, --, --check]
    pass_filenames: false
  - id: cargo-check
  - id: clippy
    args: [--, -D, warnings]
- repo: local
  hooks:
  - id: cargo-test
    name: cargo test
    entry: cargo test
    language: system
    types: [rust]
    pass_filenames: false
