[workspace]
members = [
  "keyset",
  "keyset-color",
  "keyset-core",
  "keyset-key",
]
resolver = "2"

[workspace.package]
authors = ["Lucas Jansen"]
edition = "2021"
rust-version = "1.65"
repository = "https://github.com/staticintlucas/keyset-rs"
license = "MIT OR Apache-2.0"
