name: Test

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - name: Setup tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-shear, taplo
      - name: Run rustfmt
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features
        env:
          RUSTFLAGS: -D warnings
      - name: Run cargo-shear
        run: cargo shear
      - name: Run taplo fmt
        run: taplo fmt --check
      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          arguments: --workspace --all-features

  test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, 1.82.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - name: Run cargo build
        run: cargo build
        env:
          RUSTFLAGS: -D warnings
      - name: Run cargo test
        run: cargo test --no-fail-fast --all-features

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Setup cargo-rdme
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-rdme
      - name: Build docs
        run: cargo doc --all-features --no-deps --document-private-items
        env:
          RUSTDOCFLAGS: -D warnings
      - name: Check README
        run: cargo rdme --check

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools
      - name: Setup cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - name: Show coverage
        run: cargo llvm-cov --lib
      - name: Generate coverage report
        run: cargo llvm-cov --lib --codecov --output-path lcov.info
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
          fail_ci_if_error: true
