name: Test

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
        env:
          SKIP: cargo-test
      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1

  test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, 1.65.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - name: Run cargo build
        run: cargo build
        env:
          RUSTFLAGS: -D warnings
      - name: Run cargo test
        run: cargo test

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools
      - name: Setup grcov
        run: cargo install grcov
      - name: Run cargo test
        run: cargo test --lib
        env:
          RUSTFLAGS: -Cinstrument-coverage
          LLVM_PROFILE_FILE: keyset-rs-%p-%m.profraw
      - name: Run grcov
        run: >-
          grcov .
          --source-dir .
          --binary-path ./target/debug/
          --output-type lcov
          --branch
          --llvm
          --ignore-not-existing
          --output-path ./lcov.info
          --ignore '/*'
          --excl-line '(^\s*#\[derive\([\w, ]*\)\]|unreachable!\(\))|GRCOV_EXCL_LINE'
          --excl-start 'GRCOV_EXCL_START'
          --excl-stop 'GRCOV_EXCL_STOP'
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          file: lcov.info
          fail_ci_if_error: true
